name: Deploy SOFA shop to Cloudflare
on:
  workflow_dispatch:
    inputs: {}
jobs:
  deploy-sofa-shop:
    name: Deploy
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Save public key
        run: |
          cat <<EOF > key.pem
          -----BEGIN RSA PUBLIC KEY-----
          MIICCgKCAgEAut4oj1vTo/u+o4S2E5AHduNEWmRl4zS25sJik5W80R7JI+aJOnQD
          i14mB1RYLjm4xdDabSfoSjUUXQ8GNLV389xP0yWObbbFkpaq6q1BcNlRPxjEs+Z9
          utEgiQlf+jlJZj8ohNTkqqziG2vL8rJv8ZkfXLJggK1ogFnTW1bXAaaUgEGoKiRU
          cJPpu//LsjanJnB40iTjs8iX67ZHI1iCzzZRk3x0/fKireeZlJkMjE4xrRoaudq7
          Xsbffp1W1+LUgU37pbnBjtv+u8Z+LaW7CSq+Ywqdqz2TR3r9iW6CtvS+MqDKbFcZ
          OwdMlZ1saocwo7hKfd8WZG+9vGw1J+ysiNn6OovZKKZYtHb8/LqKjadjTwUA9q1T
          u+WM3obIy8xgbi1NB/7qHXNQiOtP3xMReIFM32jsxCIYvjM9/EsJgZDnLlNEEFtd
          KNrtQ8LiQhqcLIlq1wHBEYhWYDBD8PyXCtjSwqfd5dmeosmwuMDfkY9/CkA24hcR
          QMOEjfyuazsFujl3fyBNYgT0zIzgNgEG25g4bKhEyAstY3F6gVhUxmn6C0Hh2MXk
          vjnmWMTTu8GzDHpxdfx+jYEWGKYxcOnpu1RTE6/vV8TMb7wyNfyVLD0X0Eh1MLjL
          l8SWez3iFog6pre92jXQ67BNZGGkBw/wTaHJtFMA4M2FlUi41MubfKsCAwEAAQ==
          -----END RSA PUBLIC KEY-----            
          EOF
      - name: Encrypt string
        run: echo -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" | openssl rsautl -encrypt -pubin -inkey key.pem | base64
